### ISSUE TITLE
Distinguish/Herald icons

### ISSUE THREAD

**Issue by danhab99** [danhab99/scroll-for-ruqqus#3]
**Is your feature request related to a problem? Please describe.**

`api/v1` does not return `is_distinguished` and `is_heralded` attributes for posts

**Describe the solution you'd like**

Add icons to show if a post is distinguished and/or heralded

[OC comment](https://ruqqus.com/+scrollforruqqus/post/be1o/sfr-feature-requests/yf3w)

**Comment by lithiumjs** [comment]
It will return those properties after ruqqus/ruqqus#753 is merged.
